# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5cf445a1254cbf96a5e45c029801e17a0eef8210efbc42e2627bf74b3aeb145c02429ecb25038ae523e89583da9a1169d8dd19eaacd878ff2f02117fe8733ea7

test:
  secret_key_base: 4ad9b20ddc822fb42f809e15f45ebcf13d9ab191638ef7fcdc4758ff5449d5d18010d42de62ebfd4fa0026f6f9f2eb98e42ae471fa1d9a103dc4fedbba34cc3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
